export {
  type CalendarConfig,
  DEFAULT_CONFIG,
  applyConfig,
  setWeekStartsOn,
  setSlotDuration,
  setWorkHours,
  setUse24HourTime,
  setVisibleDays,
  getSlotDuration,
  getDayStartHour,
  getDayEndHour,
  getVisibleStartHour,
  getConfig,
  useConfigLocale,
  useUse24HourTime,
  useWeekStartsOn,
  useVisibleDays,
  useWorkHours,
  useSlotDuration,
  useDayStartHour,
  useDayEndHour,
  useVisibleStartHour,
} from './calendar-config'

export { US_CONFIG, GB_CONFIG, WORKWEEK_CONFIG } from './presets'
